# Generated by Django 4.2 on 2025-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pagination_count',
            field=models.PositiveSmallIntegerField(choices=[(25, '25 записей'), (50, '50 записей'), (75, '75 записей'), (100, '100 записей')], default=50, verbose_name='Number of records per page'),
        ),
    ]
