# Generated by Django 4.2 on 2025-03-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_report_transaction_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_varchar_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Уникальный сгенерированный ID транзакции'),
        ),
    ]
