# Generated by Django 4.2 on 2025-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_transaction_transaction_varchar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_varchar_id',
            field=models.CharField(default='', max_length=10, verbose_name='Уникальный сгенерированный ID транзакции'),
            preserve_default=False,
        ),
    ]
