# Generated by Django 4.2 on 2025-03-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_transaction_transaction_varchar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
    ]
