# Generated by Django 4.2 on 2025-03-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default='2025-03-23 11:12:54.941335 +00:00'),
            preserve_default=False,
        ),
    ]
