# Generated by Django 4.2 on 2025-03-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_transaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_varchar_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='explanation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
