# Generated by Django 4.2 on 2025-03-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_transaction_transaction_varchar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
