# Generated by Django 4.2 on 2025-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_transaction_latitude_transaction_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
