# Generated by Django 4.2 on 2025-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_transaction_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_varchar_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bytes',
            field=models.PositiveSmallIntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='connect_varchar_id',
            field=models.CharField(default='', max_length=10, verbose_name='Уникальный сгенерированный ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='connection_time',
            field=models.PositiveSmallIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='port',
            field=models.PositiveSmallIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='protocol',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
