# Generated by Django 4.2 on 2025-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bytes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
