# Generated by Django 4.2 on 2025-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_transaction_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='connection_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
