# Generated by Django 4.2 on 2025-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_transaction_connection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='port',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='protocol',
            field=models.CharField(blank=True, null=True),
        ),
    ]
