# Generated by Django 4.2 on 2025-04-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_transaction_port_alter_transaction_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ip_address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
