# Generated by Django 4.2 on 2025-04-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_transaction_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='connection_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
