# Generated by Django 4.2 on 2025-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_transaction_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='firewall_rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
