# Generated by Django 4.2 on 2025-05-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_transaction_firewall_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('v1', models.FloatField()),
                ('v2', models.FloatField()),
                ('v3', models.FloatField()),
                ('v4', models.FloatField()),
                ('v5', models.FloatField()),
                ('v6', models.FloatField()),
                ('v7', models.FloatField()),
                ('v8', models.FloatField()),
                ('v9', models.FloatField()),
                ('v10', models.FloatField()),
                ('v11', models.FloatField()),
                ('v12', models.FloatField()),
                ('v13', models.FloatField()),
                ('v14', models.FloatField()),
                ('v15', models.FloatField()),
                ('v16', models.FloatField()),
                ('v17', models.FloatField()),
                ('v18', models.FloatField()),
                ('v19', models.FloatField()),
                ('v20', models.FloatField()),
                ('v21', models.FloatField()),
                ('v22', models.FloatField()),
                ('v23', models.FloatField()),
                ('v24', models.FloatField()),
                ('v25', models.FloatField()),
                ('v26', models.FloatField()),
                ('v27', models.FloatField()),
                ('v28', models.FloatField()),
                ('is_fraud', models.BooleanField(default=False)),
                ('explanation', models.TextField()),
                ('connect_varchar_id', models.CharField(max_length=10, verbose_name='ID')),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('bytes', models.IntegerField(blank=True, null=True)),
                ('connection_time', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, null=True)),
                ('firewall_rule', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.report')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
